spring:
  application:
    name: gridsandcircles
  # 자동입력 비활성화
  sql:
    init:
      mode: never
  
  # DATABASE
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  # ENV
  config:
    import: optional:file:.env[.properties]


